language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
  #- python test/databaseTest.py
deploy:
  provider: heroku
  api_key: ...
  app: twpos
